Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f9a65a85c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 9
    url(r'^create/{0,1}$', views.RCCreateView.as_view(), name='rccreateview'),
      ^
SyntaxError: invalid syntax
Performing system checks...

Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 15:41:04
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Internal Server Error: /portal/9/target-create
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 213, in get
    return super(BaseCreateView, self).get(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 104, in get_context_data
    context = super(RCCreateView, self).get_context_data(**kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
[13/Dec/2016 15:42:44] "GET /portal/9/target-create HTTP/1.1" 500 86964
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 15:41:13
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 15:44:18
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[13/Dec/2016 15:44:47] "GET /portal/9/target-create HTTP/1.1" 200 6257
[13/Dec/2016 15:44:47] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[13/Dec/2016 15:44:47] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[13/Dec/2016 15:44:47] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[13/Dec/2016 15:44:47] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[13/Dec/2016 15:44:47] "GET /static/css/main.css HTTP/1.1" 200 9160
[13/Dec/2016 15:44:47] "GET /static/css/animate.css HTTP/1.1" 200 59839
[13/Dec/2016 15:44:47] "GET /static/js/plugins.js HTTP/1.1" 200 733
[13/Dec/2016 15:44:47] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[13/Dec/2016 15:44:47] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[13/Dec/2016 15:44:47] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[13/Dec/2016 15:44:47] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[13/Dec/2016 15:44:47] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[13/Dec/2016 15:44:47] "GET /static/js/main.js HTTP/1.1" 200 1554
[13/Dec/2016 15:44:48] "GET /static/img/logo.png HTTP/1.1" 200 18815
[13/Dec/2016 15:45:04] "POST /portal/9/target-create HTTP/1.1" 302 0
[13/Dec/2016 15:45:04] "GET /portal/edit/9 HTTP/1.1" 200 11093
[13/Dec/2016 15:45:04] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:45:04] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:45:04] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 15:45:04] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 15:45:04] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 15:45:04] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 15:45:04] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 15:45:04] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[13/Dec/2016 15:45:04] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[13/Dec/2016 15:45:04] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 15:45:04] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:45:04] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:45:04] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:45:04] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 15:45:04] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 15:45:04] "GET /static/img/logo.png HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "POST /portal/edit/9 HTTP/1.1" 302 0
[13/Dec/2016 15:45:29] "GET /portal/9 HTTP/1.1" 200 10553
[13/Dec/2016 15:45:29] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:45:29] "GET /static/img/logo.png HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /portal/ HTTP/1.1" 200 12267
[13/Dec/2016 15:54:32] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:54:32] "GET /static/img/logo.png HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /portal/ HTTP/1.1" 200 12267
[13/Dec/2016 15:54:39] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 15:54:39] "GET /static/img/logo.png HTTP/1.1" 304 0
[13/Dec/2016 15:54:44] "GET /portal/9 HTTP/1.1" 200 10553
Not Found: /portal/9/target-edit/1
[13/Dec/2016 15:54:51] "GET /portal/9/target-edit/1 HTTP/1.1" 404 3506
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 15:44:25
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Internal Server Error: /portal/9/target-edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 236, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 122, in get_context_data
    context = super(TargetCreateView, self).get_context_data(**kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
[13/Dec/2016 15:55:05] "GET /portal/9/target-edit/1 HTTP/1.1" 500 87225
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 15:55:03
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 15:55:09
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[13/Dec/2016 15:55:36] "GET /portal/9/target-edit/1 HTTP/1.1" 200 6283
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 15:55:34
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[13/Dec/2016 15:56:03] "POST /portal/9/target-edit/1 HTTP/1.1" 302 0
[13/Dec/2016 15:56:04] "GET /portal/edit/9 HTTP/1.1" 200 11119
[13/Dec/2016 15:56:04] "GET /static/css/main.css HTTP/1.1" 200 9160
[13/Dec/2016 15:56:04] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[13/Dec/2016 15:56:04] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[13/Dec/2016 15:56:04] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[13/Dec/2016 15:56:04] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[13/Dec/2016 15:56:04] "GET /static/css/animate.css HTTP/1.1" 200 59839
[13/Dec/2016 15:56:04] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[13/Dec/2016 15:56:04] "GET /static/js/plugins.js HTTP/1.1" 200 733
[13/Dec/2016 15:56:04] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[13/Dec/2016 15:56:04] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[13/Dec/2016 15:56:04] "GET /static/js/main.js HTTP/1.1" 200 1554
[13/Dec/2016 15:56:04] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[13/Dec/2016 15:56:04] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[13/Dec/2016 15:56:04] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[13/Dec/2016 15:56:04] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[13/Dec/2016 15:56:04] "GET /static/img/logo.png HTTP/1.1" 200 18815
[13/Dec/2016 15:56:31] "GET /portal/9 HTTP/1.1" 200 10553
[13/Dec/2016 15:56:31] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /static/img/logo.png HTTP/1.1" 304 0
[13/Dec/2016 15:56:31] "GET /portal/9/target-create HTTP/1.1" 200 6257
[13/Dec/2016 15:56:40] "GET /portal/9/target-create HTTP/1.1" 200 6257
[13/Dec/2016 15:56:40] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:40] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:40] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:40] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:40] "GET /static/img/logo.png HTTP/1.1" 304 0
[13/Dec/2016 15:56:40] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:40] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:40] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:40] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:40] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:40] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:40] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:40] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:40] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:40] "GET /portal/9/target-edit/1 HTTP/1.1" 200 6298
[13/Dec/2016 15:56:42] "GET /portal/9/target-edit/1 HTTP/1.1" 200 6298
[13/Dec/2016 15:56:42] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:42] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:42] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:42] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:42] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:42] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:42] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 15:56:42] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:42] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:42] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:42] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:42] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:42] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:42] "GET /static/img/logo.png HTTP/1.1" 304 0
[13/Dec/2016 15:56:45] "POST /portal/9/target-edit/1 HTTP/1.1" 302 0
[13/Dec/2016 15:56:45] "GET /portal/edit/9 HTTP/1.1" 200 11119
[13/Dec/2016 15:56:45] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:56:45] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:10] "GET /portal/9/target-create HTTP/1.1" 200 6257
[13/Dec/2016 15:57:10] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:10] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:10] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:10] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:10] "GET /static/img/logo.png HTTP/1.1" 304 0
[13/Dec/2016 15:57:10] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:10] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:10] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:10] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:10] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:10] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:10] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:10] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:10] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:14] "GET /portal/9/target-edit/1 HTTP/1.1" 200 6298
[13/Dec/2016 15:57:15] "GET /portal/9/target-edit/2 HTTP/1.1" 200 6283
[13/Dec/2016 15:57:15] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:15] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:15] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:15] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:15] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:15] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:15] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:15] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:15] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:15] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:15] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:15] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:15] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:15] "GET /static/img/logo.png HTTP/1.1" 304 0
[13/Dec/2016 15:57:18] "GET /portal/9/target-edit/3 HTTP/1.1" 200 6298
[13/Dec/2016 15:57:26] "POST /portal/9/target-edit/3 HTTP/1.1" 302 0
[13/Dec/2016 15:57:26] "GET /portal/edit/9 HTTP/1.1" 200 11117
[13/Dec/2016 15:57:26] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:26] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:26] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:26] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:26] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:26] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:26] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:26] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 15:57:26] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:26] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:26] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:26] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:26] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:26] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:26] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 15:57:26] "GET /static/img/logo.png HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 15:55:40
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[13/Dec/2016 16:02:42] "GET /portal/edit/9 HTTP/1.1" 200 10812
[13/Dec/2016 16:02:42] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[13/Dec/2016 16:02:42] "GET /static/css/main.css HTTP/1.1" 200 9160
[13/Dec/2016 16:02:42] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[13/Dec/2016 16:02:42] "GET /static/css/animate.css HTTP/1.1" 200 59839
[13/Dec/2016 16:02:42] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[13/Dec/2016 16:02:42] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[13/Dec/2016 16:02:42] "GET /static/js/plugins.js HTTP/1.1" 200 733
[13/Dec/2016 16:02:42] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[13/Dec/2016 16:02:42] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[13/Dec/2016 16:02:42] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[13/Dec/2016 16:02:42] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[13/Dec/2016 16:02:42] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[13/Dec/2016 16:02:42] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[13/Dec/2016 16:02:42] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[13/Dec/2016 16:02:42] "GET /static/js/main.js HTTP/1.1" 200 1554
[13/Dec/2016 16:02:42] "GET /static/img/logo.png HTTP/1.1" 200 18815
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 16:02:39
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[13/Dec/2016 16:02:47] "GET /portal/9/target-edit/3 HTTP/1.1" 200 6296
[13/Dec/2016 16:02:47] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 16:02:47] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 16:02:47] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 16:02:47] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 16:02:47] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 16:02:47] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 16:02:47] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 16:02:47] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:02:47] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 16:02:47] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:02:47] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 16:02:47] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:02:47] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 16:02:47] "GET /static/img/logo.png HTTP/1.1" 304 0
Not Found: /portal/9/edit/
[13/Dec/2016 16:03:00] "GET /portal/9/edit/ HTTP/1.1" 404 3719
[13/Dec/2016 16:03:05] "GET /portal/edit/9 HTTP/1.1" 200 10812
[13/Dec/2016 16:03:05] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 16:03:05] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 16:03:05] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 16:03:05] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 16:03:05] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 16:03:05] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/img/logo.png HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /portal/edit/9 HTTP/1.1" 200 10812
[13/Dec/2016 16:03:06] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 16:03:06] "GET /static/img/logo.png HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 16:02:44
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[13/Dec/2016 16:04:21] "GET /static/js/main.js HTTP/1.1" 200 1554
[13/Dec/2016 16:04:21] "GET /static/img/logo.png HTTP/1.1" 200 18815
[13/Dec/2016 16:04:21] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[13/Dec/2016 16:04:21] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[13/Dec/2016 16:04:21] "GET /portal/edit/9 HTTP/1.1" 200 11030
[13/Dec/2016 16:04:21] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[13/Dec/2016 16:04:21] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[13/Dec/2016 16:04:21] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[13/Dec/2016 16:04:21] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[13/Dec/2016 16:04:21] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[13/Dec/2016 16:04:21] "GET /static/css/animate.css HTTP/1.1" 200 59839
[13/Dec/2016 16:04:21] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[13/Dec/2016 16:04:21] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[13/Dec/2016 16:04:21] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[13/Dec/2016 16:04:21] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[13/Dec/2016 16:04:21] "GET /static/css/main.css HTTP/1.1" 200 9160
[13/Dec/2016 16:04:21] "GET /static/css/animate.css HTTP/1.1" 200 59839
[13/Dec/2016 16:04:22] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[13/Dec/2016 16:04:22] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[13/Dec/2016 16:04:22] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[13/Dec/2016 16:04:22] "GET /static/js/plugins.js HTTP/1.1" 200 733
[13/Dec/2016 16:04:22] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[13/Dec/2016 16:04:22] "GET /static/js/main.js HTTP/1.1" 200 1554
[13/Dec/2016 16:04:22] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[13/Dec/2016 16:04:22] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[13/Dec/2016 16:04:22] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[13/Dec/2016 16:04:22] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[13/Dec/2016 16:04:22] "GET /static/js/plugins.js HTTP/1.1" 200 733
[13/Dec/2016 16:04:22] "GET /static/css/main.css HTTP/1.1" 200 9160
[13/Dec/2016 16:04:22] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[13/Dec/2016 16:04:22] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[13/Dec/2016 16:04:22] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[13/Dec/2016 16:04:22] "GET /static/img/logo.png HTTP/1.1" 200 18815
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 16:04:18
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[13/Dec/2016 16:04:24] "GET /portal/edit/9/target-edit/3 HTTP/1.1" 200 6296
[13/Dec/2016 16:04:24] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 16:04:24] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 16:04:24] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 16:04:24] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 16:04:24] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 16:04:24] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 16:04:24] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 16:04:24] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 16:04:24] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:04:24] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:04:24] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:04:24] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 16:04:24] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 16:04:24] "GET /static/img/logo.png HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "POST /portal/edit/9/target-edit/3 HTTP/1.1" 302 0
[13/Dec/2016 16:04:33] "GET /portal/edit/9 HTTP/1.1" 200 11033
[13/Dec/2016 16:04:33] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 16:04:33] "GET /static/img/logo.png HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 16:04:24
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f7eb0589a60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 117, in <module>
    class ResourceEditView(LoginRequiredMixin, generic.UpdateView):
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 119, in ResourceEditView
    form_class = ResourceForm
NameError: name 'ResourceForm' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fce380c7c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 117, in <module>
    class ResourceEditView(LoginRequiredMixin, generic.UpdateView):
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 119, in ResourceEditView
    form_class = ResourceForm
NameError: name 'ResourceForm' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7ff5cf627a60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 117, in <module>
    class ResourceEditView(LoginRequiredMixin, generic.UpdateView):
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 119, in ResourceEditView
    form_class = ResourceForm
NameError: name 'ResourceForm' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fd4ff22ac80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 117, in <module>
    class ResourceEditView(LoginRequiredMixin, generic.UpdateView):
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 119, in ResourceEditView
    form_class = ResourceForm
NameError: name 'ResourceForm' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7ffb622a7a60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 117, in <module>
    class ResourceEditView(LoginRequiredMixin, generic.UpdateView):
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 119, in ResourceEditView
    form_class = ResourceForm
NameError: name 'ResourceForm' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f4656770c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 117, in <module>
    class ResourceEditView(LoginRequiredMixin, generic.UpdateView):
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 119, in ResourceEditView
    form_class = ResourceForm
NameError: name 'ResourceForm' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f1c9501cc80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 9, in <module>
    url(r'^edit/(?P<rc>\d{1,9})/target-edit/(?P<pk>\d{1,9})/{0,1}$', views.TargetEditView.as_view(), name='targetedit'),
AttributeError: 'module' object has no attribute 'TargetEditView'
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f0c02c4ac80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 9, in <module>
    url(r'^edit/(?P<rc>\d{1,9})/target-edit/(?P<pk>\d{1,9})/{0,1}$', views.TargetEditView.as_view(), name='targetedit'),
AttributeError: 'module' object has no attribute 'TargetEditView'
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fcb6dd23a60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 9, in <module>
    url(r'^edit/(?P<rc>\d{1,9})/target-edit/(?P<pk>\d{1,9})/{0,1}$', views.TargetEditView.as_view(), name='targetedit'),
AttributeError: 'module' object has no attribute 'TargetEditView'
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f0eeb9a8c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 9, in <module>
    url(r'^edit/(?P<rc>\d{1,9})/target-edit/(?P<pk>\d{1,9})/{0,1}$', views.TargetEditView.as_view(), name='targetedit'),
AttributeError: 'module' object has no attribute 'TargetEditView'
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7feaeb212c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 9, in <module>
    url(r'^edit/(?P<rc>\d{1,9})/target-edit/(?P<pk>\d{1,9})/{0,1}$', views.TargetEditView.as_view(), name='targetedit'),
AttributeError: 'module' object has no attribute 'TargetEditView'
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f71c0ef4c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 9, in <module>
    url(r'^edit/(?P<rc>\d{1,9})/target-edit/(?P<pk>\d{1,9})/{0,1}$', views.TargetEditView.as_view(), name='targetedit'),
AttributeError: 'module' object has no attribute 'TargetEditView'
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f927f9d5a60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 9, in <module>
    url(r'^edit/(?P<rc>\d{1,9})/target-edit/(?P<pk>\d{1,9})/{0,1}$', views.TargetEditView.as_view(), name='targetedit'),
AttributeError: 'module' object has no attribute 'TargetEditView'
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fa4de4b5c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 9, in <module>
    url(r'^edit/(?P<rc>\d{1,9})/target-edit/(?P<pk>\d{1,9})/{0,1}$', views.TargetEditView.as_view(), name='targetedit'),
AttributeError: 'module' object has no attribute 'TargetEditView'
Performing system checks...

