Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 18:12:29
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 18:12:34
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 18:12:54] "GET /portal/edit/1 HTTP/1.1" 200 14129
[12/Dec/2016 18:12:54] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 18:12:54] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 18:12:54] "GET /static/img/logo.png HTTP/1.1" 200 18815
[12/Dec/2016 18:12:54] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 18:12:54] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 18:12:54] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 18:12:54] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 18:12:54] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 18:12:54] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 18:12:55] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 18:12:55] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 18:12:55] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 18:12:55] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 18:12:55] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 18:12:55] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 18:12:55] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 18:12:40
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 236, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 75, in get_context_data
    return redirect(self.pk)
AttributeError: 'RCEditView' object has no attribute 'pk'
[12/Dec/2016 18:13:10] "GET /static/img/logo.png HTTP/1.1" 200 18815
[12/Dec/2016 18:13:10] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 18:13:10] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 18:13:10] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 18:13:10] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 18:13:10] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 18:13:10] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 18:13:10] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 18:13:10] "GET /portal/edit/1 HTTP/1.1" 500 87479
[12/Dec/2016 18:13:10] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 18:13:10] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 18:13:10] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 18:13:10] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 18:13:10] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 18:13:10] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 18:13:10] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 18:13:10] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 18:13:07
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 18:13:14
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 18:13:38] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 236, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 75, in get_context_data
    return redirect(str(self.object.pk))
  File "/usr/local/lib/python3.4/dist-packages/django/shortcuts.py", line 56, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/django/shortcuts.py", line 147, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for '1' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[12/Dec/2016 18:13:38] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 18:13:38] "GET /static/img/logo.png HTTP/1.1" 200 18815
[12/Dec/2016 18:13:38] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 18:13:38] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 18:13:38] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 18:13:38] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 18:13:38] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 18:13:38] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 18:13:38] "GET /portal/edit/1 HTTP/1.1" 500 106913
[12/Dec/2016 18:13:38] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 18:13:38] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 18:13:38] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 18:13:38] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 18:13:38] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 18:13:38] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 18:13:38] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 18:13:35
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 236, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 75, in get_context_data
    return redirect(str(self.object.pk))
  File "/usr/local/lib/python3.4/dist-packages/django/shortcuts.py", line 56, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/django/shortcuts.py", line 147, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for '1' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[12/Dec/2016 18:14:01] "GET /static/img/logo.png HTTP/1.1" 304 0
[12/Dec/2016 18:14:01] "GET /static/js/main.js HTTP/1.1" 304 0
[12/Dec/2016 18:14:01] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[12/Dec/2016 18:14:01] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[12/Dec/2016 18:14:01] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[12/Dec/2016 18:14:01] "GET /static/css/responsive.css HTTP/1.1" 304 0
[12/Dec/2016 18:14:01] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[12/Dec/2016 18:14:01] "GET /static/css/animate.css HTTP/1.1" 304 0
[12/Dec/2016 18:14:01] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 18:14:01] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[12/Dec/2016 18:14:01] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[12/Dec/2016 18:14:01] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 18:14:01] "GET /static/css/main.css HTTP/1.1" 304 0
[12/Dec/2016 18:14:01] "GET /static/js/plugins.js HTTP/1.1" 304 0
[12/Dec/2016 18:14:01] "GET /portal/edit/1 HTTP/1.1" 500 106913
[12/Dec/2016 18:14:01] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[12/Dec/2016 18:14:01] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 18:13:40
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 18:14:26
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 18:14:33] "GET /static/img/logo.png HTTP/1.1" 200 18815
[12/Dec/2016 18:14:33] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 18:14:33] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 18:14:33] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.4/dist-packages/django/template/backends/django.py", line 64, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 267, in make_context
    context.push(original_context)
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 59, in push
    return ContextDict(self, *dicts, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 18, in __init__
    super(ContextDict, self).__init__(*args, **kwargs)
ValueError: dictionary update sequence element #0 has length 0; 2 is required
[12/Dec/2016 18:14:33] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 18:14:33] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 18:14:33] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 18:14:33] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 18:14:33] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 18:14:33] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 18:14:33] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 18:14:33] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 18:14:33] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 18:14:33] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 18:14:33] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 18:14:33] "GET /portal/edit/1 HTTP/1.1" 500 84795
[12/Dec/2016 18:14:33] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 18:14:32
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 18:15:24] "GET /static/img/logo.png HTTP/1.1" 200 18815
[12/Dec/2016 18:15:24] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 18:15:24] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.4/dist-packages/django/template/backends/django.py", line 64, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 267, in make_context
    context.push(original_context)
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 59, in push
    return ContextDict(self, *dicts, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 18, in __init__
    super(ContextDict, self).__init__(*args, **kwargs)
ValueError: dictionary update sequence element #0 has length 0; 2 is required
[12/Dec/2016 18:15:24] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 18:15:24] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 18:15:24] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 18:15:24] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 18:15:24] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 18:15:24] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 18:15:24] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 18:15:24] "GET /portal/edit/1 HTTP/1.1" 500 84844
[12/Dec/2016 18:15:24] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 18:15:25] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 18:15:25] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 18:15:25] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 18:15:25] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 18:15:25] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 18:15:21
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 18:15:27] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.4/dist-packages/django/template/backends/django.py", line 64, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 267, in make_context
    context.push(original_context)
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 59, in push
    return ContextDict(self, *dicts, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 18, in __init__
    super(ContextDict, self).__init__(*args, **kwargs)
ValueError: dictionary update sequence element #0 has length 0; 2 is required
[12/Dec/2016 18:15:27] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[12/Dec/2016 18:15:27] "GET /static/img/logo.png HTTP/1.1" 304 0
[12/Dec/2016 18:15:27] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[12/Dec/2016 18:15:27] "GET /static/css/animate.css HTTP/1.1" 304 0
[12/Dec/2016 18:15:27] "GET /static/css/responsive.css HTTP/1.1" 304 0
[12/Dec/2016 18:15:27] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[12/Dec/2016 18:15:27] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 18:15:27] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[12/Dec/2016 18:15:27] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[12/Dec/2016 18:15:27] "GET /static/js/plugins.js HTTP/1.1" 304 0
[12/Dec/2016 18:15:27] "GET /static/js/main.js HTTP/1.1" 304 0
[12/Dec/2016 18:15:27] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 18:15:27] "GET /portal/edit/1 HTTP/1.1" 500 84844
[12/Dec/2016 18:15:27] "GET /static/css/main.css HTTP/1.1" 304 0
[12/Dec/2016 18:15:27] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[12/Dec/2016 18:15:27] "GET /static/js/wow.min.js HTTP/1.1" 304 0
Not Found: /http:/www.google.com/reader/about/
[12/Dec/2016 18:54:11] "GET http://www.google.com/reader/about/ HTTP/1.1" 404 1701
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 18:15:27
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 19:23:20] "GET /static/js/main.js HTTP/1.1" 200 1554
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 236, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 75, in get_context_data
    return redirect(str(self.kwargs['pk']))
  File "/usr/local/lib/python3.4/dist-packages/django/shortcuts.py", line 56, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/django/shortcuts.py", line 147, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for '1' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[12/Dec/2016 19:23:20] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 19:23:20] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 19:23:20] "GET /static/img/logo.png HTTP/1.1" 200 18815
[12/Dec/2016 19:23:20] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 19:23:20] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 19:23:20] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 19:23:20] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 19:23:20] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 19:23:20] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 19:23:20] "GET /portal/edit/1 HTTP/1.1" 500 106935
[12/Dec/2016 19:23:20] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 19:23:21] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 19:23:21] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 19:23:21] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 19:23:21] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 19:23:21] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 19:23:17
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 19:23:24] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:24] "GET /static/img/logo.png HTTP/1.1" 304 0
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 236, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 75, in get_context_data
    return redirect(str(self.kwargs['pk']))
  File "/usr/local/lib/python3.4/dist-packages/django/shortcuts.py", line 56, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/django/shortcuts.py", line 147, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for '1' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[12/Dec/2016 19:23:24] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:24] "GET /static/css/animate.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:24] "GET /static/css/responsive.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:24] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:24] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:24] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:24] "GET /static/js/plugins.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:24] "GET /static/js/main.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:24] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:24] "GET /portal/edit/1 HTTP/1.1" 500 106935
[12/Dec/2016 19:23:24] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:24] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:24] "GET /static/css/main.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:24] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:24] "GET /static/js/wow.min.js HTTP/1.1" 304 0
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 236, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 75, in get_context_data
    return redirect(str(self.kwargs['pk']))
  File "/usr/local/lib/python3.4/dist-packages/django/shortcuts.py", line 56, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/django/shortcuts.py", line 147, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for '1' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[12/Dec/2016 19:23:25] "GET /static/img/logo.png HTTP/1.1" 304 0
[12/Dec/2016 19:23:25] "GET /static/js/main.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:25] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:25] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:25] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:25] "GET /static/css/responsive.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:25] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:25] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:25] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:25] "GET /static/css/animate.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:25] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:25] "GET /portal/edit/1 HTTP/1.1" 500 106935
[12/Dec/2016 19:23:25] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:25] "GET /static/js/plugins.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:25] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:25] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:25] "GET /static/css/main.css HTTP/1.1" 304 0
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 236, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 75, in get_context_data
    return redirect(str(self.kwargs['pk']))
  File "/usr/local/lib/python3.4/dist-packages/django/shortcuts.py", line 56, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/django/shortcuts.py", line 147, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for '1' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[12/Dec/2016 19:23:26] "GET /static/img/logo.png HTTP/1.1" 304 0
[12/Dec/2016 19:23:26] "GET /static/js/main.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:26] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:26] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:26] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:26] "GET /static/css/animate.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:26] "GET /static/css/responsive.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:26] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:26] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:26] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:26] "GET /portal/edit/1 HTTP/1.1" 500 106935
[12/Dec/2016 19:23:26] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:26] "GET /static/js/plugins.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:26] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:26] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:23:26] "GET /static/css/main.css HTTP/1.1" 304 0
[12/Dec/2016 19:23:26] "GET /static/js/wow.min.js HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 19:23:24
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 19:23:40
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 236, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 75, in get_context_data
    return redirect(str(kwargs['pk']))
KeyError: 'pk'
[12/Dec/2016 19:23:50] "GET /static/img/logo.png HTTP/1.1" 200 18815
[12/Dec/2016 19:23:50] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 19:23:50] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 19:23:50] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 19:23:50] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 19:23:50] "GET /portal/edit/1 HTTP/1.1" 500 87287
[12/Dec/2016 19:23:50] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 19:23:50] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 19:23:50] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 19:23:50] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 19:23:50] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 19:23:50] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 19:23:50] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 19:23:50] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 19:23:50] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 19:23:50] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 19:23:50] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 19:23:45
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 19:27:59] "GET /static/js/main.js HTTP/1.1" 200 1554
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.4/dist-packages/django/template/backends/django.py", line 64, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 267, in make_context
    context.push(original_context)
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 59, in push
    return ContextDict(self, *dicts, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 18, in __init__
    super(ContextDict, self).__init__(*args, **kwargs)
ValueError: dictionary update sequence element #0 has length 0; 2 is required
[12/Dec/2016 19:27:59] "GET /static/img/logo.png HTTP/1.1" 200 18815
[12/Dec/2016 19:27:59] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 19:27:59] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 19:27:59] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 19:27:59] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 19:27:59] "GET /portal/edit/1 HTTP/1.1" 500 84844
[12/Dec/2016 19:27:59] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 19:27:59] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 19:27:59] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 19:27:59] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 19:27:59] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 19:28:00] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 19:28:00] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 19:28:00] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 19:28:00] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 19:28:00] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 19:27:55
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 19:28:02
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 19:29:27] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 19:29:27] "GET /static/img/logo.png HTTP/1.1" 200 18815
[12/Dec/2016 19:29:27] "GET /portal/edit/1 HTTP/1.1" 200 14129
[12/Dec/2016 19:29:27] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 19:29:27] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 19:29:27] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 19:29:27] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 19:29:28] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 19:29:28] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 19:29:28] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 19:29:28] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 19:29:28] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 19:29:28] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 19:29:28] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 19:29:28] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 19:29:28] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 19:29:28] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 19:29:28] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 19:29:28] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 19:29:28] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 19:29:28] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 19:29:28] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 19:29:28] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 19:29:28] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 19:29:28] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 19:29:28] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 19:29:28] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[12/Dec/2016 19:29:28] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 19:29:28] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 19:29:28] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 19:29:28] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 19:29:28] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[12/Dec/2016 19:29:28] "GET /static/img/logo.png HTTP/1.1" 200 18815
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 19:29:25
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 19:29:33] "POST /portal/edit/1 HTTP/1.1" 302 0
[12/Dec/2016 19:29:33] "GET /portal/1 HTTP/1.1" 200 13581
[12/Dec/2016 19:29:33] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:29:33] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[12/Dec/2016 19:29:33] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:29:33] "GET /static/css/animate.css HTTP/1.1" 304 0
[12/Dec/2016 19:29:33] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[12/Dec/2016 19:29:33] "GET /static/css/responsive.css HTTP/1.1" 304 0
[12/Dec/2016 19:29:33] "GET /static/css/main.css HTTP/1.1" 304 0
[12/Dec/2016 19:29:33] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:29:33] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:29:33] "GET /static/js/plugins.js HTTP/1.1" 304 0
[12/Dec/2016 19:29:33] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:29:33] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[12/Dec/2016 19:29:33] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:29:33] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:29:33] "GET /static/js/main.js HTTP/1.1" 304 0
[12/Dec/2016 19:29:33] "GET /static/img/logo.png HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 19:29:31
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 19:31:00] "GET /static/img/logo.png HTTP/1.1" 200 18815
[12/Dec/2016 19:31:00] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 19:31:00] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 19:31:00] "GET /portal/edit/1 HTTP/1.1" 200 14129
[12/Dec/2016 19:31:00] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 19:31:00] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 19:31:00] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 19:31:00] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 19:31:00] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 19:31:00] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 19:31:00] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 19:31:00] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 19:31:00] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 19:31:00] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 19:31:00] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 19:31:00] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 19:31:00] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[12/Dec/2016 19:31:00] "GET /static/img/logo.png HTTP/1.1" 304 0
[12/Dec/2016 19:31:00] "GET /static/js/main.js HTTP/1.1" 304 0
[12/Dec/2016 19:31:00] "GET /portal/edit/1 HTTP/1.1" 200 14129
[12/Dec/2016 19:31:00] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[12/Dec/2016 19:31:00] "GET /static/css/responsive.css HTTP/1.1" 304 0
[12/Dec/2016 19:31:00] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:31:00] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:31:00] "GET /static/js/plugins.js HTTP/1.1" 304 0
[12/Dec/2016 19:31:00] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:31:00] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 19:31:00] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:31:00] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:31:00] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 19:31:00] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 19:31:00] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 19:31:00] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 19:31:00] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 19:31:00] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 19:31:01] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 19:31:01] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 19:31:01] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 19:31:01] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 19:31:01] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 19:31:01] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 19:31:01] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 19:31:01] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[12/Dec/2016 19:31:01] "GET /static/img/logo.png HTTP/1.1" 200 18815
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 19:30:55
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 240, in post
    return super(BaseUpdateView, self).post(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 94, in form_valid
    return redirect("/portal/" + str(self.kwargs['pak']))
KeyError: 'pak'
[12/Dec/2016 19:31:05] "POST /portal/edit/1 HTTP/1.1" 500 88287
Not Found: /http:/testp4.pospr.waw.pl/testproxy.php
[12/Dec/2016 19:31:32] "GET http://testp4.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1721
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 19:31:02
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 19:33:11] "GET /static/img/logo.png HTTP/1.1" 200 18815
[12/Dec/2016 19:33:11] "GET /portal/edit/1 HTTP/1.1" 200 14129
[12/Dec/2016 19:33:11] "GET /static/js/main.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:11] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:11] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:11] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:11] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 19:33:11] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 19:33:11] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 19:33:11] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 19:33:11] "GET /static/js/plugins.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:11] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 19:33:11] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 19:33:11] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:11] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 19:33:11] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 19:33:11] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 19:33:11] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 19:33:11] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 19:33:11] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:11] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:11] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 19:33:11] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:11] "GET /static/js/plugins.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:11] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 19:33:11] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:11] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:12] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:12] "GET /static/js/main.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:12] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 19:33:12] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:12] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:33:12] "GET /static/img/logo.png HTTP/1.1" 200 18815
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 19:33:10
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 19:33:21] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:21] "GET /static/css/responsive.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:21] "GET /static/img/logo.png HTTP/1.1" 304 0
[12/Dec/2016 19:33:21] "GET /portal/edit/1 HTTP/1.1" 200 14129
[12/Dec/2016 19:33:21] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:21] "GET /static/css/animate.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:21] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:21] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:21] "GET /static/css/main.css HTTP/1.1" 304 0
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 240, in post
    return super(BaseUpdateView, self).post(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 95, in form_valid
    return redirect("/portal/" + str(context[object].id))
KeyError: <class 'object'>
[12/Dec/2016 19:33:24] "POST /portal/edit/1 HTTP/1.1" 500 89755
[12/Dec/2016 19:33:46] "GET /portal/edit/1 HTTP/1.1" 200 14129
[12/Dec/2016 19:33:46] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:46] "GET /static/img/logo.png HTTP/1.1" 304 0
[12/Dec/2016 19:33:46] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 19:33:46] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 19:33:46] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 19:33:47] "GET /static/css/responsive.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:47] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 19:33:47] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:47] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:47] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:47] "GET /static/css/animate.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:47] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:47] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:47] "GET /static/css/main.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:47] "GET /static/css/animate.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:47] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:47] "GET /static/css/responsive.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:47] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 19:33:47] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:47] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 19:33:47] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 19:33:47] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 19:33:47] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 19:33:47] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 19:33:47] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 19:33:47] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 19:33:47] "GET /static/css/main.css HTTP/1.1" 304 0
[12/Dec/2016 19:33:47] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[12/Dec/2016 19:33:47] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 19:33:47] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 19:33:47] "GET /static/img/logo.png HTTP/1.1" 304 0
[12/Dec/2016 19:33:47] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 240, in post
    return super(BaseUpdateView, self).post(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 95, in form_valid
    return redirect("/portal/" + str(context[object].id))
KeyError: <class 'object'>
[12/Dec/2016 19:33:50] "POST /portal/edit/1 HTTP/1.1" 500 89755
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 19:33:16
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 19:34:01] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 19:34:01] "GET /static/img/logo.png HTTP/1.1" 200 18815
[12/Dec/2016 19:34:01] "GET /portal/edit/1 HTTP/1.1" 200 14129
[12/Dec/2016 19:34:01] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 19:34:01] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 19:34:01] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 19:34:01] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 19:34:01] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 19:34:01] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 19:34:01] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 19:34:01] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 19:34:01] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 19:34:01] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 19:34:01] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 19:34:01] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 19:34:01] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 19:34:01] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 19:34:01] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 19:34:01] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 19:34:01] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 19:34:01] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 19:34:01] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 19:34:01] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 19:34:01] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 19:34:01] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[12/Dec/2016 19:34:01] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 19:34:01] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 19:34:01] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 19:34:01] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 19:34:01] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 19:34:01] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 19:34:02] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[12/Dec/2016 19:34:02] "GET /static/img/logo.png HTTP/1.1" 200 18815
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 19:33:59
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 19:34:07] "GET /static/js/main.js HTTP/1.1" 304 0
[12/Dec/2016 19:34:07] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:34:07] "GET /portal/edit/1 HTTP/1.1" 200 14129
[12/Dec/2016 19:34:07] "GET /static/img/logo.png HTTP/1.1" 304 0
[12/Dec/2016 19:34:07] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:34:07] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[12/Dec/2016 19:34:07] "GET /static/css/animate.css HTTP/1.1" 304 0
[12/Dec/2016 19:34:07] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[12/Dec/2016 19:34:07] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:34:07] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[12/Dec/2016 19:34:07] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[12/Dec/2016 19:34:07] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:34:07] "GET /static/js/plugins.js HTTP/1.1" 304 0
[12/Dec/2016 19:34:07] "GET /static/css/main.css HTTP/1.1" 304 0
[12/Dec/2016 19:34:07] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:34:07] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[12/Dec/2016 19:34:07] "GET /static/css/responsive.css HTTP/1.1" 304 0
Internal Server Error: /portal/edit/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 240, in post
    return super(BaseUpdateView, self).post(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 95, in form_valid
    return redirect("/portal/" + str(context[object].pk))
KeyError: <class 'object'>
[12/Dec/2016 19:34:10] "POST /portal/edit/1 HTTP/1.1" 500 89755
Not Found: /http:/www.baidu.com/favicon.ico
[13/Dec/2016 01:18:50] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1691
[13/Dec/2016 02:33:04] "GET / HTTP/1.0" 200 12083
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 19:34:04
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fa3ce240a60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 101, in <module>
    class TargetCreateView(LoginRequiredMixin, generic.CreateView):
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 103, in TargetCreateView
    form_class    = TargetForm
NameError: name 'TargetForm' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f938f577c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 101, in <module>
    class TargetCreateView(LoginRequiredMixin, generic.CreateView):
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 103, in TargetCreateView
    form_class    = TargetForm
NameError: name 'TargetForm' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f83e61daa60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 101, in <module>
    class TargetCreateView(LoginRequiredMixin, generic.CreateView):
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 103, in TargetCreateView
    form_class    = TargetForm
NameError: name 'TargetForm' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f04c68e4c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 101, in <module>
    class TargetCreateView(LoginRequiredMixin, generic.CreateView):
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 103, in TargetCreateView
    form_class    = TargetForm
NameError: name 'TargetForm' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fba3ab70c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 101, in <module>
    class TargetCreateView(LoginRequiredMixin, generic.CreateView):
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 103, in TargetCreateView
    form_class    = TargetForm
NameError: name 'TargetForm' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f4f74205bf8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 101, in <module>
    class TargetCreateView(LoginRequiredMixin, generic.CreateView):
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 103, in TargetCreateView
    form_class    = TargetForm
NameError: name 'TargetForm' is not defined
Performing system checks...

Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 04:17:39
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 04:17:41
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[13/Dec/2016 04:17:46] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
Internal Server Error: /portal/edit/7
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 235, in get
    self.object = self.get_object()
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/detail.py", line 32, in get_object
    queryset = self.get_queryset()
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/detail.py", line 74, in get_queryset
    'cls': self.__class__.__name__
django.core.exceptions.ImproperlyConfigured: RCEditView is missing a QuerySet. Define RCEditView.model, RCEditView.queryset, or override RCEditView.get_queryset().
[13/Dec/2016 04:17:46] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[13/Dec/2016 04:17:46] "GET /portal/edit/7 HTTP/1.1" 500 86243
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 04:17:42
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Internal Server Error: /portal/edit/7
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 235, in get
    self.object = self.get_object()
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/detail.py", line 32, in get_object
    queryset = self.get_queryset()
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/detail.py", line 74, in get_queryset
    'cls': self.__class__.__name__
django.core.exceptions.ImproperlyConfigured: RCEditView is missing a QuerySet. Define RCEditView.model, RCEditView.queryset, or override RCEditView.get_queryset().
[13/Dec/2016 04:18:11] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:18:11] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:18:11] "GET /portal/edit/7 HTTP/1.1" 500 86243
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 04:17:50
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 04:18:45
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 04:18:46
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[13/Dec/2016 04:18:55] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[13/Dec/2016 04:18:55] "GET /portal/edit/7 HTTP/1.1" 200 10927
[13/Dec/2016 04:18:55] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[13/Dec/2016 04:18:55] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[13/Dec/2016 04:18:55] "GET /static/css/main.css HTTP/1.1" 200 9160
[13/Dec/2016 04:18:55] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[13/Dec/2016 04:18:55] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[13/Dec/2016 04:18:55] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[13/Dec/2016 04:18:55] "GET /static/css/animate.css HTTP/1.1" 200 59839
[13/Dec/2016 04:18:55] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[13/Dec/2016 04:18:55] "GET /static/js/plugins.js HTTP/1.1" 200 733
[13/Dec/2016 04:18:55] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[13/Dec/2016 04:18:55] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[13/Dec/2016 04:18:55] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[13/Dec/2016 04:18:55] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[13/Dec/2016 04:18:55] "GET /static/js/main.js HTTP/1.1" 200 1554
[13/Dec/2016 04:18:55] "GET /static/img/logo.png HTTP/1.1" 200 18815
[13/Dec/2016 04:19:03] "POST /portal/edit/7 HTTP/1.1" 302 0
[13/Dec/2016 04:19:03] "GET /portal/7 HTTP/1.1" 200 10360
[13/Dec/2016 04:19:03] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 04:19:04] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 04:19:04] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 04:19:04] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 04:19:04] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 04:19:04] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 04:19:04] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:19:04] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 04:19:04] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:19:04] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 04:19:04] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:19:04] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:19:04] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:19:04] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 04:19:04] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 04:19:04] "GET /static/img/logo.png HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 04:18:54
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 04:24:19
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[13/Dec/2016 04:24:27] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[13/Dec/2016 04:24:27] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[13/Dec/2016 04:24:27] "GET /static/js/plugins.js HTTP/1.1" 200 733
[13/Dec/2016 04:24:27] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[13/Dec/2016 04:24:27] "GET /portal/ HTTP/1.1" 200 12003
[13/Dec/2016 04:24:27] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[13/Dec/2016 04:24:27] "GET /static/css/animate.css HTTP/1.1" 200 59839
[13/Dec/2016 04:24:27] "GET /static/img/logo.png HTTP/1.1" 200 18815
[13/Dec/2016 04:24:28] "GET /static/js/main.js HTTP/1.1" 200 1554
[13/Dec/2016 04:24:28] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[13/Dec/2016 04:24:28] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[13/Dec/2016 04:24:28] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[13/Dec/2016 04:24:28] "GET /static/css/main.css HTTP/1.1" 200 9160
[13/Dec/2016 04:24:28] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[13/Dec/2016 04:24:28] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[13/Dec/2016 04:24:28] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[13/Dec/2016 04:24:28] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[13/Dec/2016 04:24:29] "GET /portal/create/ HTTP/1.1" 200 10233
[13/Dec/2016 04:24:29] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:48] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:48] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:48] "GET /portal/create/ HTTP/1.1" 200 10233
[13/Dec/2016 04:24:48] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 04:24:48] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:49] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:24:49] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 04:24:50] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 04:24:50] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:24:50] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:50] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:50] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:50] "GET /portal/create/ HTTP/1.1" 200 10233
[13/Dec/2016 04:24:51] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:24:51] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:52] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:52] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:52] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:24:52] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:24:54] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 04:24:57] "GET /portal/create/ HTTP/1.1" 200 10233
[13/Dec/2016 04:24:57] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:57] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 04:24:57] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:57] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:58] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:58] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:58] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:58] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:58] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:58] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:58] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:24:58] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:24:58] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:58] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 04:24:58] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 04:24:58] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:24:58] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 04:25:13] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 04:25:13] "GET /static/img/logo.png HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "POST /portal/create/ HTTP/1.1" 302 0
[13/Dec/2016 04:25:27] "GET /portal/edit/9 HTTP/1.1" 200 10912
[13/Dec/2016 04:25:27] "GET /static/css/animate.css HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "GET /static/css/main.css HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "GET /static/css/responsive.css HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "GET /static/js/plugins.js HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "GET /static/js/main.js HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[13/Dec/2016 04:25:27] "GET /static/img/logo.png HTTP/1.1" 304 0
[13/Dec/2016 04:25:31] "POST /portal/edit/9 HTTP/1.1" 302 0
[13/Dec/2016 04:25:31] "GET /portal/9 HTTP/1.1" 200 10346
[13/Dec/2016 04:25:31] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[13/Dec/2016 04:25:31] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
Not Found: /portal/9/target-create
[13/Dec/2016 04:29:39] "GET /portal/9/target-create HTTP/1.1" 404 3287
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 04:24:27
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 04:29:51
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 13, 2016 - 04:29:52
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f89573a2c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 9
    url(r'^create/{0,1}$', views.RCCreateView.as_view(), name='rccreateview'),
      ^
SyntaxError: invalid syntax
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fbd196bcc80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 9
    url(r'^create/{0,1}$', views.RCCreateView.as_view(), name='rccreateview'),
      ^
SyntaxError: invalid syntax
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f58a7c19c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 9
    url(r'^create/{0,1}$', views.RCCreateView.as_view(), name='rccreateview'),
      ^
SyntaxError: invalid syntax
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f3c62191bf8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 9
    url(r'^create/{0,1}$', views.RCCreateView.as_view(), name='rccreateview'),
      ^
SyntaxError: invalid syntax
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fbc0aee8c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 9
    url(r'^create/{0,1}$', views.RCCreateView.as_view(), name='rccreateview'),
      ^
SyntaxError: invalid syntax
Performing system checks...

